plugins {
    id 'com.android.application'
}

android {
    namespace 'com.livewallpapers'
    compileSdk 34
    
    defaultConfig {
        applicationId "com.livewallpapers"
        minSdk 15
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    signingConfigs {
        spe {
            def propsFile = file("../keystore/special.properties")
            if (propsFile.exists()) {
                Properties props = new Properties()
                props.load(new FileInputStream(propsFile))
                storeFile file(props['key.store'])
                storePassword props['key.store.password']
                keyAlias props['key.alias']
                keyPassword props['key.alias.password']
            }
        }
    }
    
    flavorDimensions += "theme"
    productFlavors {
        redhearts {
            dimension "theme"
            applicationId "com.livewallpaper.redhearts"
            versionCode rootProject.ext.themeVersionCode
            versionName rootProject.ext.themeVersionName
            signingConfig signingConfigs.spe
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // Enable BuildConfig generation
    buildFeatures {
        buildConfig true
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
        baseline file("lint-baseline.xml")
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation project(':andengine')
    implementation project(':andengine_box2d')
    implementation project(':andenginelivewallpaperextension')
}
